### ISSUE TITLE
issue importing text blob

### ISSUE THREAD

**Issue by ouverz** [sloria/TextBlob#101]
Hi everyone!

I am trying to import the TextBlob module in my python script through PyCharm (OS X)but nothing I do works. My project interpreter is Anaconda.
I have been trying to load the module through the 'Project Interpreter' in the Preferences screen, however I cannot find the module to begin with. I tried downloading the module zip file and copy it into <anaconda path>/pkgs/textblob but the module doesn't appear on any of the lists of available modules.
This is the code I am using : from textblob import TextBlob
I also tried loading the conda module however I was unsure of how to load the TextBlob module with it.
Also, I install textblob via PIP into site-packages.
Please advise.

**Comment by jschnurr** [comment]
Closed for inactivity.
