### ISSUE TITLE
memory error performing noun phrases on (small) text

### ISSUE THREAD

**Issue by darenr** [sloria/TextBlob#106]
The following self contained examples causes a **memory error**

Linux (Ubuntu) 4.2.0-22-generic
Python 2.7.10
textblob-0.11.0

```
from textblob import Blobber
from textblob.en.np_extractors import ConllExtractor

tb = Blobber(np_extractor=ConllExtractor())

text = """
 Marina Abramovic
 Cabelo 
 Janet Cardiff
 Bonnie Collura
 Minerva Cuevas
 Tacita Dean
 Jose Antonio Hernandez-Diez
 Olafur Eliasson 
 Arturo Herrera
 Sharon Lockhart
 Ken Lum
 Fabian Marcaccio
 Paul McCarthy
 Lee Mingwei
 Beatriz Milhazes
 Ernesto Neto
 Gabriel Orozco
 Jorge Pardo
 The Poetics Project, Mike Kelley and Tony Oursler
 Marjetica Potrc
 Paul Ramirez-Jonas
 Karim Rashid
 Meyer Vaisman
 Adriana Varejao
 Andrea Zittel
"""

b = tb(text)
print b.noun_phrases

```

**Comment by darenr** [comment]
Note: this appears to be related to the sequence of proper nouns (artist names) - when they are joined with a period instead of newline the issue goes away.

**Comment by jschnurr** [comment]
I can't reproduce this, even using `textblob-0.11.0` and `nltk-3.1`. It also appears that [nltk.ChunkParserI](https://github.com/nltk/nltk/blob/develop/nltk/chunk/__init__.py) (from which ConllExtractor is based) is very stable.

If more information comes to light, please re-open the issue.
