### ISSUE TITLE
Unable to translate a text file

### ISSUE THREAD

**Issue by nixfreak** [sloria/TextBlob#107]
Please let me know if I am doing this wrong? 

I'm trying to open and read a text file with multiple keywords and phrases in different languages.
I would like to be able to translate this using a case statement if at all possible.
Every time I try to pass a file format I get an error stating "only strings" 

Is there a way to pass in a file to the translate module? 

from textblob import TextBlob

> > > myfile = open('keywords' ,'r')
> > > blob = TextBlob(myfile)

  File "/usr/local/lib/python2.7/dist-packages/textblob/blob.py", line 346, in _
_init__
    'must be a string, not {0}'.format(type(text)))
TypeError: The `text` argument passed to `__init__(text)` must be a string, not
<type 'file'>

Any help would be greatly appreciated.

Thanks in advance

**Comment by chandra589** [comment]
I am also having a similar problem.
my code
for i,text in enumerate(tweets.text):
    blob = TextBlob(text)
    tweets.text[i] = blob.correct()

error
TypeError: The `text` argument passed to `__init__(text)` must be a string, not <class 'textblob.blob.TextBlob'>

can someone please help

**Comment by chandra589** [comment]
TypeError: The `text` argument passed to `__init__(text)` must be a string, not <class 'textblob.blob.TextBlob'>

**Comment by chandra589** [comment]
I am also having a similar problem.

my code

for i,text in enumerate(tweets.text):
blob = TextBlob(text)
tweets.text[i] = blob.correct()

error:
Traceback (most recent call last):
  File "savingtweetstodb.py", line 63, in <module>
    blob = TextBlob(text)
  File "/usr/local/lib/python2.7/dist-packages/textblob/blob.py", line 344, in __init__
    'must be a string, not {0}'.format(type(text)))
TypeError: The `text` argument passed to `__init__(text)` must be a string, not <class 'textblob.blob.TextBlob'>

can someone please help
Thanks

**Comment by sloria** [comment]
You must pass the string to be translated to `TextBlob`, not a file pointer.

```python
with open('keywords', 'r') as fp:
     content = fp.read()
blob = TextBlob(content)
```

**Comment by chandra589** [comment]
I am kind of new to python, so i exactly could not get what you are saying
what i have is a database named tweets, out of which one column is text field. so i wanted to correct every sentence by looping into every cell in that text column

Thanks a lot

**Comment by jschnurr** [comment]
@chandra589 Given your code above:
```python
for i,text in enumerate(tweets.text):
  blob = TextBlob(text)
```
... the error suggests that the `tweets.text` object is an iterable of `textblob.blob.TextBlob` objects - not strings. You're trying to turn a Textblob into a Textblob, and you can't do that - you need to supply a string.

Closing for now - please comment if this is still an issue.
