### ISSUE TITLE
Is there a way to include punctuation into a tagged sentence tuple?

### ISSUE THREAD

**Issue by tastyminerals** [sloria/TextBlob#112]
Right now a tagged sentence does not contain punctuation:
`('Suddenly', u'RB'), ('she', u'PRP'), ('came', u'VBD'), ('upon', u'IN'), ('a', u'DT'), ('little', u'JJ'), ('table', u'NN')`

Is there a way to include punctuation?

**Comment by nitkul** [comment]
@tastyminerals there is a line in `tokenizers.py` which says it's possible:

`def tokenize(self, text, include_punc=True):`

@sloria not sure if I can call this function directly

**Comment by tastyminerals** [comment]
Yep, the option is described in the docstring (must not have been mentioned in the docs though). Closing.
