### ISSUE TITLE
POS-tagging does not work in TextBlob

### ISSUE THREAD

**Issue by tastyminerals** [sloria/TextBlob#121]
I have read on [**textblob_aptagger**](github.com/sloria/textblob-aptagger) page that *"As of TextBlob 0.11.0, TextBlob uses NLTK's averaged perceptron tagger by default. This package is no longer necessary."*

However if we check it: 
```
In [1]: import textblob as txt
In [2]: txt.taggers.
txt.taggers.BaseTagger txt.taggers.NLTKTagger txt.taggers.PatternTagger txt.taggers.absolute_import
```
There is no `PerceptronTagger`, unless it is `NLTKTagger`.
Can you please comment on this? 
Because now, when I explicitly do not use  **textblob_aptagger** package and attempt to pos-tag my text as:
```
blob = Blobber()
parsed_text = blob(text)
```
The application freezes and text never gets pos-tagged.

*UPDATED:*
Ah, I found it in nltk, ``from nltk.tag.perceptron import PerceptronTagger``
However when I use it with **textblob**:
```
from nltk.tag.perceptron import PerceptronTagger
nltk_tagger = PerceptronTagger()
blob = Blobber(pos_tagger=nltk_tagger)
parsed_text = blob(text)
```

This code freezes the application as well.
Here is a trace:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/tastyminerals/dev/nn-search2/nn-search2/model.py", line 143, in process_text
    blob = Blobber(pos_tagger=nltk_tagger)
  File "/usr/lib/python2.7/site-packages/textblob/blob.py", line 733, in __init__
    parser, classifier)
  File "/usr/lib/python2.7/site-packages/textblob/blob.py", line 306, in _initialize_models
    BaseTagger, BaseBlob.pos_tagger)
  File "/usr/lib/python2.7/site-packages/textblob/blob.py", line 290, in _validated_param
    .format(name=name, cls=base_class_name))
ValueError: pos_tagger must be an instance of BaseTagger
```

**Comment by tastyminerals** [comment]
Another thing. I tried to follow [this pos-tagging example](http://textblob.readthedocs.org/en/dev/advanced_usage.html) and it appears to freeze everything as well.
```
from textblob.taggers import NLTKTagger
nltk_tagger = NLTKTagger()
blob = Blobber(pos_tagger=nltk_tagger)
parsed_text = blob(text)
```

**Comment by sloria** [comment]
The `NLTKTagger` in TextBlob *is* the AveragedPerceptron tagger; it is the default algorithm used by NLTK's tagger.

Not sure why your code example is freezing, though. How large is the text you are tagging?

**Comment by tastyminerals** [comment]
I see.
I am running the above code in a separate thread while running a progress bar that shows the text is being processed. When the separate thread is finished I kill the progress bar window. However, it never gets killed if I use the example provided in your wiki. It works ok with *deprecated* ``textblob_aptagger`` package installed.
For example:
```
from textblob_aptagger import PerceptronTagger
blob = Blobber(pos_tagger=PerceptronTagger())
parsed_text = blob(text)
```
There is no problem with the above code, it works nice while:
```
from textblob.taggers import NLTKTagger
nltk_tagger = NLTKTagger()
blob = Blobber(pos_tagger=nltk_tagger)
parsed_text = blob(text)
```
The above however shows the progress bar forever, so it looks like `self.process_thread.is_alive()`` is always ``True``. Why is this happening is a good question.

If you have a little time you can clone [my application](https://github.com/tastyminerals/nn-search.git) install the dependencies ``python2 setup.py install`` and then you'll have to replace ``from textblob.packages import nltk`` to ``import nltk`` in
``python2.7/site-packages/textblob_aptagger-0.2.0-py2.7.egg/textblob_aptagger/taggers.py``.

**Comment by tastyminerals** [comment]
So, current solution for me is actually clone your latest ``textblob_aptagger`` (not the one from PyPI), package it into `.whl` and install it separately. 
Since this is ok for me, I just want you to know that there is something wrong with current **TextBlob** pos-tagger implementation.

**Comment by tastyminerals** [comment]
It appears I used `from textblob import Blobber` import instead of `from textblob import TextBlobber`
and the working the the latter.
`Blobber` was working forever while `TextBlobber` did his job in a few seconds.
