### ISSUE TITLE
Error when importing textblob

### ISSUE THREAD

**Issue by liranmaymoni** [sloria/TextBlob#124]
Hey,
Using windows 10
I've install textblob using "py -m pip install textblob".
I can import textblob, or from textblob import blob,word
But i cant: from textblobl import Textblob.
The error i get is:
Traceback (most recent call last):
  File "<pyshell#5>", line 1, in <module>
    from textblob import Textblob
ImportError: cannot import name 'Textblob'

Thanks.

**Comment by sloria** [comment]
What version of textblob are you using? Do you happen do have a file in your project called `textblob.py`?

**Comment by jschnurr** [comment]
Closed for inactivity.

**Comment by kurianbenoy** [comment]
I recently realised naming textblob.py causes errors

Thanks @sloria

**Comment by Dimanjan** [comment]
Thanks @kurianbenoy

**Comment by hmabubakar313** [comment]
I am using ubuntu in windows 10 which they have given as an app in windows 10. I am facing the following error
ImportError: cannot import name textblob

**Comment by A94-M** [comment]
first 
pip download textblob
and from textblob import Word

**Comment by pipoyopop** [comment]
Isn't it about B like TextBlob?
