### ISSUE TITLE
Inaccurate result

### ISSUE THREAD

**Issue by kessilover** [sloria/TextBlob#125]
So when I want to evaluate "Thank you for all your hard work", using the sentiment.polarity method returns a negative value!
I'm assuming that "hard" is the reason for that.

**Comment by sloria** [comment]
TextBlob's default sentiment analyzer uses the lookup-based analyzer from [pattern](http://www.clips.ua.ac.be/pattern). Please report this issue on that project. Thanks!

**Comment by kessilover** [comment]
Thank you.
