### ISSUE TITLE
ImportError: No module named text.blob

### ISSUE THREAD

**Issue by datomnurdin** [sloria/TextBlob#132]
I got this error message when trying to run the script even already installed via pip.

```
Traceback (most recent call last):
  File "TF-IDF.py", line 2, in <module>
    from text.blob import TextBlob as tb
ImportError: No module named text.blob
```

My script

```
import math
from text.blob import TextBlob as tb
```

Please advice. Thank you.

**Comment by sloria** [comment]
The correct import is 

```python
from textblob import TextBlob as tb
```

**Comment by salman28th** [comment]
If you see the script it is " from text.blob" instead it should be "from textblob"
Try using 
from textblob imort textblob as tb
