### ISSUE TITLE
Download of textblob.download_corpora failed | SSL error

### ISSUE THREAD

**Issue by gaurikatyagi** [sloria/TextBlob#133]
[nltk_data] Error loading brown: <urlopen error [SSL:
[nltk_data]     CERTIFICATE_VERIFY_FAILED] certificate verify failed
[nltk_data]     (_ssl.c:590)>
[nltk_data] Error loading punkt: <urlopen error [SSL:
[nltk_data]     CERTIFICATE_VERIFY_FAILED] certificate verify failed
[nltk_data]     (_ssl.c:590)>
[nltk_data] Error loading wordnet: <urlopen error [SSL:
[nltk_data]     CERTIFICATE_VERIFY_FAILED] certificate verify failed
[nltk_data]     (_ssl.c:590)>
[nltk_data] Error loading averaged_perceptron_tagger: <urlopen error
[nltk_data]     [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify
[nltk_data]     failed (_ssl.c:590)>
[nltk_data] Error loading conll2000: <urlopen error [SSL:
[nltk_data]     CERTIFICATE_VERIFY_FAILED] certificate verify failed
[nltk_data]     (_ssl.c:590)>
[nltk_data] Error loading movie_reviews: <urlopen error [SSL:
[nltk_data]     CERTIFICATE_VERIFY_FAILED] certificate verify failed
[nltk_data]     (_ssl.c:590)>
Finished.

**Ubuntu Xenial**

**Comment by tanzeelak** [comment]
I have the same problem! Did you ever solve this issue?

**Comment by lvm** [comment]
Still failing but this isn't a TextBlob issue but a NLTK issue, an alternative is to download manually the files that failed to download from [here](http://www.nltk.org/nltk_data/) and extract them to:  
    Windows: C:\nltk_data\
    OSX: /usr/local/share/nltk_data/
    Unix: /usr/share/nltk_data/

**Comment by tstreamDOTh** [comment]
same issue

**Comment by philipkiely** [comment]
Still broken

**Comment by DeepNeuron** [comment]
Also still broken ^

**Comment by j-js** [comment]
I downloaded anaconda and re-install text blob and it is working

**Comment by sachinjnd** [comment]
Just run this command on OSX before downloading:
/Applications/Python\ 3.6/Install\ Certificates.command

**Comment by jschnurr** [comment]
Appears to affects OSX only, workaround from @sachinjnd should work. More info [on SO](https://stackoverflow.com/a/42890688/4108524) and [Python bug tracker](https://bugs.python.org/issue28150). No fix required in TextBlob - closing for now.
