### ISSUE TITLE
pyinstaller issue

### ISSUE THREAD

**Issue by smalldatascaled** [sloria/TextBlob#134]
Having a problem using textblob with pyinstaller (so that it can run on machines without python).

I create this file as TestTextBlob.py:

`from textblob import TextBlob`
`blobject = TextBlob("Gee, I really love how textblob automatically scores sentences for polarity. But I really hate how it works with pyinstaller.")`
`for sent in blobject.sentences:`
`print('Sentence: %s   |    Polarity: %s' % (sent,sent.polarity))`

When I run it I get a polarity of 0.5 and -0.8

Then, I turn this file into an exe using:

`pyinstaller --onefile --clean --noupx "C:\path\LaunchTestSearch.py"`

However, when I run the exe now, the polarity (and subjectivity) come out as zero. 

I'm trying to follow through the pyinstaller help (https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs) but as textblob is not generating any errors that I can see, I'm not sure where to start debugging?

Thanks

**Comment by jschnurr** [comment]
See #185.
