### ISSUE TITLE
how to input from csv file for classifier

### ISSUE THREAD

**Issue by traincroft** [sloria/TextBlob#142]
I've tried to follow the tutorial for a Naive Bayes classifier (https://textblob.readthedocs.io/en/dev/classifiers.html).  I formatted data files as stated -- each line contains an un-punctuated sentence, then a comma, then a class.  I've tried to read these files using several different csv input packages.  I've tried converting the sentence (only) of each row into a textblog.  I've also tried skipping that step.  I can't seem to convert the rows from the file into the proper format for classifying new records.  The training step goes fine.  However, when I try to classify from a second file (formatted in exactly the same way), I always get "basic_extractor() takes exactly 2 arguments (1 given)" .

It would be so nice if someone could post a simple example of how to read and format from a training file, and the same for a testing file, and then show how those values are given to the training and testing phases.

thanks

**Comment by traincroft** [comment]
Here is a simplified version of my problem:

from textblob.classifiers import NaiveBayesClassifier
import csv
import sys

simpletext = []
sometext   = []
with open('simple1.csv','r') as simple:
  sometext = csv.reader(simple)
  for row in sometext:
    tblb = ()
    tblb = (row[0],row[1])
    simpletext.append(tblb)

nbcl = NaiveBayesClassifier(simpletext)

testworthy = []
testable   = []
with open('simple2.csv','r') as testthis:
  testable = csv.reader(testthis)
  for row in testable:
    tblb = ()
    tblb = (row[0],row[1])
    testworthy.append(tblb)

nbcl.classify(testworthy)

With the following two toy files:

simple1.csv
this is a sentence, pos
another sentence is here, neg
i would like this to work, pos
but maybe it will not, neg

simple2.csv
i do not know if this will work, pos
it would be nice if it would work, pos
but nothing is certain in this world, neg

thanks

**Comment by traincroft** [comment]
With help from colleagues Praveen Ravichandran and Yasaman Khazaeni, we have a solution.  Despite the confusing error message, the classify method wants only a single argument, which is the text to be classified.  If you give it the text *and* the ground-truth classification (same format as the training data), it fails, and paradoxically tells you that you gave it one argument while it was expecting two arguments.

Here is the revised toy script, which uses the same files as above:

from textblob.classifiers import NaiveBayesClassifier
import csv
import sys

simpletext = []
sometext   = []

with open('simple1.csv','r') as simple:
  sometext = csv.reader(simple)
  for row in sometext:
    # print 'row1 ', row
    tblb = ()
    tblb = (row[0],row[1])
    simpletext.append(tblb)

nbcl = NaiveBayesClassifier(simpletext)

testworthy = []
testable   = []
with open('simple2.csv','r') as testthis:
  testable = csv.reader(testthis)
  for row in testable:
    # print 'testable ', row
    tblb = ()
    tblb = (row[0],row[1])
    testworthy.append(tblb)

for row in testworthy:
  print row[0], ' classified as ', nbcl.classify(row[0]), ' with ground_truth ', row[1]

**Comment by Munduruca** [comment]
I used a NaiveBayesClassifier to create a classifier which I saved as a pickle.
Now I'm not being able to reload the serialised classifier to analyse new events.
I tried this:
model_handler = open('NaiveBayesClassifier_v2k.pickle', 'rb')
model = pickle.load(model_handler)
model_handler.close()
classifier = NaiveBayesClassifier(model)
print(classifier.classify("This cheese is terrible!"))
