### ISSUE TITLE
Saving Naive Bayes Classifier

### ISSUE THREAD

**Issue by chenc17** [sloria/TextBlob#144]
Hi!

Does anyone know if there is a way to save a Naive Bayes Classifier (like to a file)? I have a static training set, so it would be great if I didn't have to recreate the same classifier every time the program runs.

Thanks!

**Comment by vmesel** [comment]
@chenc17 what is the library that you are using to build the classifier?

**Comment by chenc17** [comment]
@vmesel I'm using the textblob.classifiers module (i.e. "from textblob.classifiers import NaiveBayesClassifier"). Thanks for the link, I will look into that!
