### ISSUE TITLE
Stemming within textblob

### ISSUE THREAD

**Issue by shawnhind** [sloria/TextBlob#145]
Hello,

I'm new to using this package so I'm sorry if I'm missing something obvious here.

From what I can see, textblob is able to do lemmitization using NLTK's lemmatizer but it is not able to do the same with stemming.

There are times when stemming is the preferred way to go over lemmitization.  Is there a reason this was not included or would this be a valid feature request?

**Comment by nitkul** [comment]
@shawnhind hey I realized this might be a genuine problem. Not sure if 'no stemming' was the intent here, but I wrote a function for it and submitted a PR to @sloria
