### ISSUE TITLE
Issue with .correct() 

### ISSUE THREAD

**Issue by nyborrobyn** [sloria/TextBlob#151]
I'm just testing out TextBlob and in particular the spelling functionality. Perhaps I'm missing something, but the basic example of the .correct() method is returning an empty Texblob. (I'm using Python 2.7 in Jupyter Notebooks). Other Texblob functionality has worked as expected/demonstrated in docs. 

input:
phrase = TextBlob("Do you get thaksgiving day off?")
phrase.correct()

output: 
TextBlob("")

**Comment by sloria** [comment]
I cannot reproduce this issue. What version of TextBlob are you using?

```
pip freeze | grep -i textblob
```

**Comment by rp-navera** [comment]
Tried it again after reinstalling everything on machine with pip instead of anaconda. It is now working.
