### ISSUE TITLE
How to remove stop words in TextBlobs?

### ISSUE THREAD

**Issue by srinidhibhat** [sloria/TextBlob#153]
I am doing text classification using TextBlob. I am giving the training dataset through a JSON file. But I'm finding difficulty in removing stop words. Please help.
[tb.txt](https://github.com/sloria/TextBlob/files/785642/tb.txt)

**Comment by lifeofzi** [comment]
Same problem here, let me look into the documentation once more.

**Comment by lifeofzi** [comment]
@srinidhibhat 
Try using the following :

```
from textblob import TextBlob
from textblob import Blobber
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
```
 Let's make our stopset:
`stop_words = set(['the', 'and', 'a' ,'an'])`

Let's say we have the following string
`b="the quick brown fox jumped over a lazy dog.  "`

Converting our string b to set of words and subtracting the stopset from it 
`sub_stopwords =  set(blob.words) - stopset`

Now we prepare our output string from this set
```
final_string=' '
for word in sub_stopwords:
    final_string=final_string + word +' '
print final_string
```
Output `quick brown lazy fox jumped `
