### ISSUE TITLE
How to extract the named entity from the text

### ISSUE THREAD

**Issue by sanyam199** [sloria/TextBlob#154]
I need to find the named entity or entity from the text. But i did not find anything related in the docs.
I got a something from the textblob library

`
from polyglot.text import Text
blob = """The Israeli Prime Minister Benjamin Netanyahu has warned that Iran poses a "threat to the entire world"."""
text = Text(blob)

text = Text(blob, hint_language_code='en')

print text.entities
[I-ORG([u'Israeli']), I-PER([u'Benjamin', u'Netanyahu']), I-LOC([u'Iran'])]
`
This is using the polyglot. Is any way to find entites using the textblob library ?

**Comment by MaxwellRebo** [comment]
`[thing[0] for thing in blob.tags if thing[1] == u'NNP']`
