### ISSUE TITLE
ModuleNotFoundError: No module named '_sqlite3'

### ISSUE THREAD

**Issue by arnieadm35** [sloria/TextBlob#173]
Hello,

I'm migrating my script from my Mac to a AWS Linux instance. I upgraded the AWS instance to Python 3.6 before importing packages, including textbook. Now I get this error and cannot find where it's coming from. I'm not the greatest python programmer, but I did have it running perfectly on my Mac before installing it on AWS.

Here's the entire Traceback:

Traceback (most recent call last):
  File "wikiparser20170801.py", line 8, in <module>
    from textblob import TextBlob
  File "/usr/local/lib/python3.6/site-packages/textblob/__init__.py", line 9, in <module>
    from .blob import TextBlob, Word, Sentence, Blobber, WordList
  File "/usr/local/lib/python3.6/site-packages/textblob/blob.py", line 28, in <module>
    import nltk
  File "/usr/local/lib/python3.6/site-packages/nltk/__init__.py", line 137, in <module>
    from nltk.stem import *
  File "/usr/local/lib/python3.6/site-packages/nltk/stem/__init__.py", line 29, in <module>
    from nltk.stem.snowball import SnowballStemmer
  File "/usr/local/lib/python3.6/site-packages/nltk/stem/snowball.py", line 26, in <module>
    from nltk.corpus import stopwords
  File "/usr/local/lib/python3.6/site-packages/nltk/corpus/__init__.py", line 66, in <module>
    from nltk.corpus.reader import *
  File "/usr/local/lib/python3.6/site-packages/nltk/corpus/reader/__init__.py", line 105, in <module>
    from nltk.corpus.reader.panlex_lite import *
  File "/usr/local/lib/python3.6/site-packages/nltk/corpus/reader/panlex_lite.py", line 15, in <module>
    import sqlite3
  File "/usr/local/lib/python3.6/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.6/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3

**Comment by arnieadm35** [comment]
I just launched a new ubuntu AWS instance, installed pip3, textblob, and wget, and it's working perfectly. The ubuntu instance comes default with python 3.5. So, now I don't know if 3.6 is the problem or if my first Linux AWS EC2 instance was broken.

**Comment by TamasNeumer** [comment]
Hi!

I think this is unrelated to TextBolb. I'm new to python but i ran into the same problem yesterday. I used pyenv and somehow sqlite was not build/installed and I was missing the _sqlite3 as well.
In order to solve it I did the following:
- `sudo apt-get install libsqlite3-dev`
- (Or you can install more packages as suggested on the [pyenv wiki](https://github.com/pyenv/pyenv/wiki): `apt-get install -y make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev xz-utils tk-dev`
- Now in the downloaded python source rebuild and install python with the following command: `./configure --enable-loadable-sqlite-extensions && make && sudo make install`

Anyway the key thing for me was to have the libsqlite3-dev installed and then rebuild/install with the correct flags.

Hope it helps. If did, then please close the ticket.

**Comment by arnieadm35** [comment]
Yes, I agree. While I'm curious why libsqlite3 didn't install on it's own, it doesn't appear to be a TextBlob error. I'm closing the issue.

**Comment by arnieadm35** [comment]
Thank you. Closed.

**Comment by TamasNeumer** [comment]
You are welcome. Happy coding ;-)

**Comment by skyfore** [comment]
@TamasNeumer  Thks ! It's very helpful for me.

**Comment by sbodanapu** [comment]
Hi Tamas,
I dont have permission to install the libsqlite3-dev. I have downloaded the source code for sqlite3.
Please let me know in which directory I have to keep it while building the python with --enable-loadable-sqlite-extensions option.
Thanks!

**Comment by gittigxuy** [comment]
@TamasNeumer ,If I use pyenv and python3.6,my system is ubuntu14.04,how could I do this step?


`Now in the downloaded python source rebuild and install python with the following command: ./configure --enable-loadable-sqlite-extensions && make && sudo make install`

**Comment by mastanbol** [comment]
sqlite3 will comes with python itself. I also get the same problem i just uninstalled the python3.6 and installed again.

uninstall existing python:

sudo apt-get remove --purge python3.6

Install python3.6:

sudo apt install build-essential checkinstall

sudo apt install libreadline-gplv2-dev libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev

wget https://www.python.org/ftp/python/3.6.0/Python-3.6.0.tar.xz

tar xvf Python-3.6.0.tar.xz

cd Python-3.6.0/

./configure

sudo make altinstall

It works!

**Comment by vibnimit** [comment]
Thanks @mastanbol this worked for me.

**Comment by absognety** [comment]
> sqlite3 will comes with python itself. I also get the same problem i just uninstalled the python3.6 and installed again.
> 
> uninstall existing python:
> 
> sudo apt-get remove --purge python3.6
> 
> Install python3.6:
> 
> sudo apt install build-essential checkinstall
> 
> sudo apt install libreadline-gplv2-dev libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev
> 
> wget https://www.python.org/ftp/python/3.6.0/Python-3.6.0.tar.xz
> 
> tar xvf Python-3.6.0.tar.xz
> 
> cd Python-3.6.0/
> 
> ./configure
> 
> sudo make altinstall
> 
> It works!

This worked for me also!!!

**Comment by absognety** [comment]
> Hi!
> 
> I think this is unrelated to TextBolb. I'm new to python but i ran into the same problem yesterday. I used pyenv and somehow sqlite was not build/installed and I was missing the _sqlite3 as well.
> In order to solve it I did the following:
> 
> * `sudo apt-get install libsqlite3-dev`
> * (Or you can install more packages as suggested on the [pyenv wiki](https://github.com/pyenv/pyenv/wiki): `apt-get install -y make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev xz-utils tk-dev`
> * Now in the downloaded python source rebuild and install python with the following command: `./configure --enable-loadable-sqlite-extensions && make && sudo make install`
> 
> Anyway the key thing for me was to have the libsqlite3-dev installed and then rebuild/install with the correct flags.
> 
> Hope it helps. If did, then please close the ticket.

`./configure --enable-loadable-sqlite-extensions && make && sudo make install` resulted in  
```
PermissionError: [Errno 13] Permission denied: 'build/lib.linux-x86_64-3.8/_sysconfigdata__linux_x86_64-linux-gnu.py'

```
When I removed `make` and replaced `install` with `altinstall` it worked. I installed `python 3.8` from source and was trying to rebuild it because of `ModuleNotFoundError: No module named '_sqlite3'` issue

**Comment by neicras** [comment]
Where would I find the "downloaded python source"?

**Comment by neicras** [comment]
> Hi!
> 
> I think this is unrelated to TextBolb. I'm new to python but i ran into the same problem yesterday. I used pyenv and somehow sqlite was not build/installed and I was missing the _sqlite3 as well.
> In order to solve it I did the following:
> 
> * `sudo apt-get install libsqlite3-dev`
> * (Or you can install more packages as suggested on the [pyenv wiki](https://github.com/pyenv/pyenv/wiki): `apt-get install -y make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev xz-utils tk-dev`
> * Now in the downloaded python source rebuild and install python with the following command: `./configure --enable-loadable-sqlite-extensions && make && sudo make install`
> 
> Anyway the key thing for me was to have the libsqlite3-dev installed and then rebuild/install with the correct flags.
> 
> Hope it helps. If did, then please close the ticket.

Here where would I find the "downloaded python source"?

**Comment by zenconnect** [comment]
On the [python website](https://www.python.org/downloads/source/) @neicras

**Comment by TomHejret** [comment]
In my case it was due to installing `sudo apt-get install libsqlite3-dev` AFTER installing Python. So I installed `libsqlite3-dev` and re-installed Python and it works.

**Comment by p1yu5h0** [comment]
> sqlite3 will comes with python itself. I also get the same problem i just uninstalled the python3.6 and installed again.
> 
> uninstall existing python:
> 
> sudo apt-get remove --purge python3.6
> 
> Install python3.6:
> 
> sudo apt install build-essential checkinstall
> 
> sudo apt install libreadline-gplv2-dev libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev
> 
> wget https://www.python.org/ftp/python/3.6.0/Python-3.6.0.tar.xz
> 
> tar xvf Python-3.6.0.tar.xz
> 
> cd Python-3.6.0/
> 
> ./configure
> 
> sudo make altinstall
> 
> It works!

Worked For me!!

**Comment by pratt3000** [comment]
> 

how do I rebuild from source? could you specify the directory pl/
