### ISSUE TITLE
classifier size is too large 

### ISSUE THREAD

**Issue by chetandev** [sloria/TextBlob#175]
Hi , I am saving classifier using pickle . and loading the pickle while classifying new messages 
Pickle loading takes a lot of time to load as the size is too large (148 mb) for only 1000 messages for training
here is the sample code 

 ```
if os.path.isfile('textclassifier.pickle'):
     print('in')
     f=  open('textclassifier.pickle', 'rb')
     cl = pickle.load(f)
     f.close()
else:
     print('out')
     with open('train.csv', 'r') as fp:
        cl = NaiveBayesClassifier(fp, format="csv")
     f = open('textclassifier.pickle', 'wb')
     pickle.dump(cl,f)
     f.close()
```

**Comment by Gabriel-p** [comment]
I've experienced the same issue. Dumping a `NaiveBayesClassifier()` instance results in an excessively large file, at least when `pickle` is used.

**Comment by jschnurr** [comment]
Two things to try.

1. cPickle - uses the same interface, but is much faster.
```python
import cPickle as pickle
pickle.dump(cl,f)
```
2. Use a newer version of the Pickle protocol. The default is backwards compatible, but also old and slow compared with newer implementations.  See this answer on [StackOverflow](https://stackoverflow.com/a/23582505/4108524).
```python
pickle.dump(cl, f, -1)  # -1 forces highest protocol
```

In my test using 2000 records, these two changes reduced the time to create `textclassifier.pickle` from `32 seconds` to `12`, the load time from `11 seconds` to `5`, and the file size from `354M` to `245M`.

Let me know if that helps.

**Comment by chetandev** [comment]
@Gabriel-p I  did the same thing

**Comment by jschnurr** [comment]
Makes sense - when performance matters, Sklearn is much more optimized.
