### ISSUE TITLE
How to calculate the accuracy of NaiveBayesAnalyzer for Sentiment Analysis

### ISSUE THREAD

**Issue by k153017** [sloria/TextBlob#183]
NaiveBayesAnalyzer is pre trained i want to use it it on a new test set it will give the result. but the problem is how to test its accuracy for the new set

**Comment by jschnurr** [comment]
Creating, training and evaluating your own classifier is described in the [docs](http://textblob.readthedocs.io/en/dev/classifiers.html#evaluating-classifiers).  Is there something missing?
