### ISSUE TITLE
Tried to lemmatize the word 'Went' and received the output as 'Went' instead of 'go' as capital W was used

### ISSUE THREAD

**Issue by yupitsme** [sloria/TextBlob#184]

**Comment by jschnurr** [comment]
I don't understand.  Can you please post a [MCVE](https://stackoverflow.com/help/mcve)?

**Comment by yupitsme** [comment]
>>> from textblob import Word
>>> w = Word("went")
>>> w.lemmatize("v")     # Pass in WordNet part of speech (verb)
'go'
>>> # In the above case we tried to find the lemmatized word of "went" and
>>> # received the output as "go" which is the correct lemmatized word we expect as output
>>> 
>>> # Let's try to find the lemmatized words for "Went" and "WENT".
>>> # Ideally, we want the outputs for both the above words to be "go"
>>> # But, we get the lemmatized output for the word "Went" as "Went" and the output "WENT" for "WENT" as seen below
>>> w = Word("Went")
>>> w.lemmatize("v")     # Pass in WordNet part of speech (verb)
'Went'
>>> w = Word("WENT")
>>> w.lemmatize("v")     # Pass in WordNet part of speech (verb)
'WENT'
>>> # Unless we expect the user to use .lower function to convert the words to
>>> # lowercase before using them in the lemmatize function, in which case, the above issue can be closed
>>> # Closing this issue as lowercase function can be used prior to lemmatizing the word to avoid it
