### ISSUE TITLE
Error while import textblob

### ISSUE THREAD

**Issue by darmawiguna** [sloria/TextBlob#188]
I am new in python. I have problem while importing textblob
While i write from textblob import TextBlob, it appears error below:

> ` 22 from wordcloud import WordCloud
>      23 from sklearn.feature_extraction.text import CountVectorizer
> ---> 24 from textblob import TextBlob
>      25 from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory
>      26 from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
> 
> ~/anaconda3/lib/python3.6/site-packages/textblob/__init__.py in <module>()
>       1 import os
> ----> 2 from .blob import TextBlob, Word, Sentence, Blobber, WordList
>       3 
>       4 __version__ = '0.15.1'
>       5 __license__ = 'MIT'
> 
> ~/anaconda3/lib/python3.6/site-packages/textblob/blob.py in <module>()
>      26 from collections import defaultdict
>      27 
> ---> 28 import nltk
>      29 
>      30 from textblob.decorators import cached_property, requires_nltk_corpus
> 
> ~/anaconda3/lib/python3.6/site-packages/nltk/__init__.py in <module>()
>     126 ###########################################################
>     127 
> --> 128 from nltk.chunk import *
>     129 from nltk.classify import *
>     130 from nltk.inference import *
> 
> ~/anaconda3/lib/python3.6/site-packages/nltk/chunk/__init__.py in <module>()
>     155 from nltk.data import load
>     156 
> --> 157 from nltk.chunk.api import ChunkParserI
>     158 from nltk.chunk.util import (ChunkScore, accuracy, tagstr2tree, conllstr2tree,
>     159                              conlltags2tree, tree2conlltags, tree2conllstr, tree2conlltags,
> 
> ~/anaconda3/lib/python3.6/site-packages/nltk/chunk/api.py in <module>()
>      13 from nltk.parse import ParserI
>      14 
> ---> 15 from nltk.chunk.util import ChunkScore
>      16 
>      17 class ChunkParserI(ParserI):
> 
> ~/anaconda3/lib/python3.6/site-packages/nltk/chunk/util.py in <module>()
>      11 
>      12 from nltk.tree import Tree
> ---> 13 from nltk.tag.mapping import map_tag
>      14 from nltk.tag.util import str2tuple
>      15 from nltk.compat import python_2_unicode_compatible
> 
> ~/anaconda3/lib/python3.6/site-packages/nltk/tag/__init__.py in <module>()
>      68 from nltk.tag.api           import TaggerI
>      69 from nltk.tag.util          import str2tuple, tuple2str, untag
> ---> 70 from nltk.tag.sequential    import (SequentialBackoffTagger, ContextTagger,
>      71                                     DefaultTagger, NgramTagger, UnigramTagger,
>      72                                     BigramTagger, TrigramTagger, AffixTagger,
> 
> ~/anaconda3/lib/python3.6/site-packages/nltk/tag/sequential.py in <module>()
>      24 
>      25 from nltk.probability import ConditionalFreqDist
> ---> 26 from nltk.classify import NaiveBayesClassifier
>      27 from nltk.compat import python_2_unicode_compatible
>      28 
> 
> ~/anaconda3/lib/python3.6/site-packages/nltk/classify/__init__.py in <module>()
>      96                                   ConditionalExponentialClassifier)
>      97 from nltk.classify.senna import Senna
> ---> 98 from nltk.classify.textcat import TextCat
> 
> ~/anaconda3/lib/python3.6/site-packages/nltk/classify/textcat.py in <module>()
>      45 # You may have to "pip install regx"
>      46 try:
> ---> 47     import regex as re
>      48 except ImportError:
>      49     re = None
> 
> ~/anaconda3/lib/python3.6/site-packages/regex.py in <module>()
>     681 
>     682 # We define _pattern_type here after all the support objects have been defined.
> --> 683 _pattern_type = type(_compile("", 0, {}))
>     684 
>     685 # We'll define an alias for the 'compile' function so that the repr of a
> 
> ~/anaconda3/lib/python3.6/site-packages/regex.py in _compile(pattern, flags, kwargs)
>     434     if _locale_sensitive.get(locale_key, True) or (flags & LOCALE) != 0:
>     435         # This pattern is, or might be, locale-sensitive.
> --> 436         pattern_locale = _getlocale()[1]
>     437     else:
>     438         # This pattern is definitely not locale-sensitive.
> 
> ~/anaconda3/lib/python3.6/locale.py in getlocale(category)
>     579     if category == LC_ALL and ';' in localename:
>     580         raise TypeError('category LC_ALL is not supported')
> --> 581     return _parse_localename(localename)
>     582 
>     583 def setlocale(category, locale=None):
> 
> ~/anaconda3/lib/python3.6/locale.py in _parse_localename(localename)
>     488     elif code == 'C':
>     489         return None, None
> --> 490     raise ValueError('unknown locale: %s' % localename)
>     491 
>     492 def _build_localename(localetuple):
> ValueError: unknown locale: UTF-8

I have tried to add 
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
but still error. Please help. Thank you.

**Comment by jschnurr** [comment]
Please post a complete example of the code you're running, and format the error [correctly](https://guides.github.com/features/mastering-markdown/) - this is very difficult to read.

**Comment by darmawiguna** [comment]
It worked already. Thank you so much.
