### ISSUE TITLE
Error finishing textblob install

### ISSUE THREAD

**Issue by cliff88** [sloria/TextBlob#197]
trying to install textblob  on a Mac, but the second step doesn't work
Any suggestions??
Also, not sure why pip got installed as pip3 ????

$ pip3 install -U textblob
Collecting textblob
  Downloading textblob-0.15.1-py2.py3-none-any.whl (631kB)
    100% |████████████████████████████████| 634kB 1.5MB/s 
Collecting nltk>=3.1 (from textblob)
  Downloading nltk-3.2.5.tar.gz (1.2MB)
    100% |████████████████████████████████| 1.2MB 1.1MB/s 
Collecting six (from nltk>=3.1->textblob)
  Downloading six-1.11.0-py2.py3-none-any.whl
Installing collected packages: six, nltk, textblob
  Running setup.py install for nltk ... done
Successfully installed nltk-3.2.5 six-1.11.0 textblob-0.15.1

$ python -m textblob.download_corpora
/usr/bin/python: No module named textblob

**Comment by jschnurr** [comment]
The python versions do not match - you installed to version 3 using `pip3`, but are trying to run with version 2 using `python` (not `python3`).  

Try `python3 -m textblob.download_corpora`.

**Comment by cliff88** [comment]
Much better!  I had to get some certificates installed, but it looks like it worked.

Opened an IDLE window and I can't seem to get the textblob to work, though

Python 3.6.4 (v3.6.4:d48ecebad5, Dec 18 2017, 21:07:28) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "copyright", "credits" or "license()" for more information.
>>> WARNING: The version of Tcl/Tk (8.5.9) in use may be unstable.
Visit http://www.python.org/download/mac/tcltk/ for current information.

>>> text = 'this is a test string'
>>> blob = TextBlob(text)
Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    blob = TextBlob(text)
NameError: name 'TextBlob' is not defined

**Comment by wanjeraO** [comment]
Was this ever resolved? I get the same Textblob not defined error. But everything seems to be well installed. I am confused - Any help would be highly appreciated. Thanks

**Comment by hustler-1-0-1** [comment]
Im getting the sameTextblob not defined error
How come its working for other people???
