### ISSUE TITLE
Portuguese Language Support

### ISSUE THREAD

**Issue by brunojus** [sloria/TextBlob#202]
I'd like to analyze the sentiment in brazilian tweets. TextBlob has anyone method to analyze direct in Portuguese or I need to translate?

In this moment, I'm doing with this code:

def analize_sentiment(tweet):
    analysis = TextBlob(tweet)
    if analysis.detect_language() != 'en':
        analysis = TextBlob(str(analysis.translate(to='en')))
        return analysis.sentiment.polarity
    else:
        return analysis.sentiment.polarity

Thanks

**Comment by sloria** [comment]
There is no built-in support for Portuguese at this time.

**Comment by HenriqueAJNBranco** [comment]
Any chances of this to happen? I'd like to see it working in other languages, mainly portuguese
