### ISSUE TITLE
Stop word removal

### ISSUE THREAD

**Issue by rcprati** [sloria/TextBlob#21]
Create a method that returns the text blob without stop words.

**Comment by morganics** [comment]
Old topic, but I was a bit surprised there was no method of getting a textblob/ wordlist without stopwords, as it's fairly basic functionality (even if it is simple). Now I'll have to import NLTK to get their stopword list, as well as use textblob, which I feel rather removes the point.

**Comment by shahdarshil** [comment]
@sloria your solution seems pretty goods but i implemented the same it doesn't works
