### ISSUE TITLE
how can I use Chinese language sentiment analysis

### ISSUE THREAD

**Issue by RajeshkannanRamakrishnan** [sloria/TextBlob#211]
am trying to do sentiment analysis for Chinese language. it's not working properly. I added training data also it's not working

**Comment by NewtonGaliza** [comment]
Hello Rajesh, i have a problem like you, i want to sentiment analysis for portuguese language. I solved the problem tranlating the tweet in portugues (i´m was checking the analysis of some hashtag), to english and use the translation on sentiment analysis.

**Comment by sloria** [comment]
TextBlob's default sentiment analyzer only supports English at the moment. I recommend using @NewtonGaliza 's workaround: translate to English before analyzing.
