### ISSUE TITLE
HTTP Error 503: Service Unavailable while using detect_language() and translate() from textblob

### ISSUE THREAD

**Issue by craigchen1990** [sloria/TextBlob#215]
python:3.5
textblob:0.15.1

seems it happened before and fixed in #148 

the detail logs
`  File "/usr/local/lib/python3.5/site-packages/textblob/blob.py", line 562, in detect_language
    return self.translator.detect(self.raw) `
`  File "/usr/local/lib/python3.5/site-packages/textblob/translate.py", line 72, in detect
    response = self._request(url, host=host, type_=type_, data=data)`
`  File "/usr/local/lib/python3.5/site-packages/textblob/translate.py", line 92, in _request
    resp = request.urlopen(req) `
`  File "/usr/local/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout) `
`  File "/usr/local/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response) `
`  File "/usr/local/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs) `
`  File "/usr/local/lib/python3.5/urllib/request.py", line 504, in error
    result = self._call_chain(*args) `
`  File "/usr/local/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args) `
`  File "/usr/local/lib/python3.5/urllib/request.py", line 696, in http_error_302
    return self.parent.open(new, timeout=req.timeout) `
`  File "/usr/local/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response) `
`  File "/usr/local/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs) `
`  File "/usr/local/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args) `
`  File "/usr/local/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args) `
`  File "/usr/local/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)`

**Comment by craigchen1990** [comment]
and i make some tests and look like `sl=auto&tl=en&hl=en&dt=at&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&dt=t&ie=UTF-8&oe=UTF-8&otf=1&ssel=0&tsel=0&kc=4` works in browser

**Comment by iharshulhan** [comment]
I have the same issue, it appears that google blocks a request and asks to solve captcha

**Comment by Jor-G-ete** [comment]
I have the same problem with my code. 
I belive this error migth be happeing due to Google isn't free anymore. So they let you to compute some tanslations untill they reject you from the server. 

I changed my ip, and it let me try more words , but when It reached the maximun(418 words translated), it denied the connection again. So that's my guess

**Comment by JinwookKim** [comment]
Yeah, getting the same issue here as well.

**Comment by RajeshkannanRamakrishnan** [comment]
yes am also facing same issue

**Comment by daviligade** [comment]
Me too.

**Comment by EduardoSebastianRodriguez** [comment]
As I have read in some forums, there is a problem in the generation of the virtual identity for Google. In general, in all the functions of the library in which the Google tools are used, it is needed an ID to contact Google and ask for their services. Then, Google analyzes it and decides if the message comes from a robot or from a real user. In order to avoid that, Textblob uses an algorithm to generate de identity. However, Google seems to have updated its protocols, so now the algorithm does not work anymore.
The solution is to update the library, using the default library REQUEST of Python, to generate the IDs.

This is the solution I can propose, I cannot confirm its funcionality, but i think is more than nothing :) I hope this post can help others and the responables of the library solving these issues, because in other case the library is completely unuseful.

**Comment by sergeiGKS** [comment]
Am facing the same issue. 

Any update?

**Comment by sloria** [comment]
Again, please do not post any more "+1" comments. I encourage anyone to send a PR resolving this.

**Comment by Fernandohf** [comment]
A temporary workaround for `detect_language` could be using the port [langdetect](https://github.com/Mimino666/langdetect). Could run the code bellow without the **HTTP Error 503**. 
```python
from langdetect import detect
for i in range(1000):
    print(detect('Hello World'))
```
Keep in mind the this doesn't solve the error to `translate` method.

**Comment by KishoreKonakanti** [comment]
@Fernandohf , langdetect's ability of identifying the languages seems to be very poor:

langdetect.detect('bonjour') # Supposed to be French but ended up Croatian
Out[97]: 'hr'

langdetect.detect('hi') # English /Swedish
Out[98]: 'sw'

langdetect.detect('hello') #English/ Finnish
Out[99]: 'fi'_ 
PS: Language codes interpreted as in ISO 639-2

Thank you.

**Comment by alihashaam** [comment]
@sloria is this issue resolved and fixed in v0.15.3?

**Comment by sloria** [comment]
No, this is still an issue.

**Comment by amritsh** [comment]
The TextBlob translate works on mac, but fails on linux with just the first request throwing 503 error, tried specifying linux environment in the user agent of request, still 503, probably I am missing something

**Comment by Ashish-Bansal** [comment]
Since it's open issue, I'm adding to it. 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mrphantom/leetcode/venv/lib/python3.6/site-packages/textblob/blob.py", line 568, in detect_language
    return self.translator.detect(self.raw)
  File "/home/mrphantom/leetcode/venv/lib/python3.6/site-packages/textblob/translate.py", line 72, in detect
    response = self._request(url, host=host, type_=type_, data=data)
  File "/home/mrphantom/leetcode/venv/lib/python3.6/site-packages/textblob/translate.py", line 92, in _request
    resp = request.urlopen(req)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 564, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 756, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests
```

According to the comments I read in the thread (works fine on few requests and then 503 etc etc.), seems like earlier Google was sending wrong response code. I'm not getting 503 instead 429 error which means my requests are being blocked intentionally by Google. 429 is normally used by rate limiters to notify that client should slow down. Right now it's happening for me even on first request from my server's static IP which may mean they are blocking it due to the "human" check. 

Anyway, I think the implementation of the detect_language is wrong. If it really depends on the Google Translate, then it should be using the Google API token specified in the https://cloud.google.com/translate/docs/translating-text instead of calling the API endpoint meant for their frontend code.

**Comment by RuikunLi** [comment]
> Since it's open issue, I'm adding to it.
> 
> ```
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/mrphantom/leetcode/venv/lib/python3.6/site-packages/textblob/blob.py", line 568, in detect_language
>     return self.translator.detect(self.raw)
>   File "/home/mrphantom/leetcode/venv/lib/python3.6/site-packages/textblob/translate.py", line 72, in detect
>     response = self._request(url, host=host, type_=type_, data=data)
>   File "/home/mrphantom/leetcode/venv/lib/python3.6/site-packages/textblob/translate.py", line 92, in _request
>     resp = request.urlopen(req)
>   File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
>     return opener.open(url, data, timeout)
>   File "/usr/lib/python3.6/urllib/request.py", line 532, in open
>     response = meth(req, response)
>   File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
>     'http', request, response, code, msg, hdrs)
>   File "/usr/lib/python3.6/urllib/request.py", line 564, in error
>     result = self._call_chain(*args)
>   File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
>     result = func(*args)
>   File "/usr/lib/python3.6/urllib/request.py", line 756, in http_error_302
>     return self.parent.open(new, timeout=req.timeout)
>   File "/usr/lib/python3.6/urllib/request.py", line 532, in open
>     response = meth(req, response)
>   File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
>     'http', request, response, code, msg, hdrs)
>   File "/usr/lib/python3.6/urllib/request.py", line 570, in error
>     return self._call_chain(*args)
>   File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
>     result = func(*args)
>   File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
>     raise HTTPError(req.full_url, code, msg, hdrs, fp)
> urllib.error.HTTPError: HTTP Error 429: Too Many Requests
> ```
> 
> According to the comments I read in the thread (works fine on few requests and then 503 etc etc.), it seems like earlier Google was sending wrong response code. I'm not getting 429 instead of 503 which means my requests are being blocked intentionally by Google. 429 is normally used by rate limiters to notify that client should slow down. Right now it's happening for me even on first request from my server's static IP which may mean they are blocking it due to the "human" check.
> 
> Anyway, I think the implementation of the detect_language is wrong. If it really depends on the Google Translate, then it should be using the Google API token specified in the https://cloud.google.com/translate/docs/translating-text instead of calling the API endpoint meant for their frontend code.

I have the same issue!

**Comment by sloria** [comment]
I think it's time we remove the language detection and translate features. They use an undocumented/unsupported Google API, which is why they no longer work.

**Comment by bharaniid** [comment]
Is there any updates. Still i am facing same issue.

**Comment by sloria** [comment]
For anyone finding this issue, I recommend taking a look at https://github.com/ssut/py-googletrans or [official Google Translate API](https://cloud.google.com/translate/docs) as a substitute for TextBlob's translation functionality
