### ISSUE TITLE
what paper method/ algorithm is used for sentiment analysis?

### ISSUE THREAD

**Issue by Sandy4321** [sloria/TextBlob#220]
what paper method/ algorithm is used for sentiment analysis?
how good is it, what performance are?
Thanks

**Comment by sloria** [comment]
The default sentiment analyzer just delegates to pattern.en, which uses a dictionary-based algorithm: https://www.clips.uantwerpen.be/pages/pattern-en#sentiment . According to the docs, the accuracy is about 75% for movie reviews.

**Comment by woctezuma** [comment]
For info, the webpage does not exist anymore, but I guess it is about this: https://github.com/clips/pattern
