### ISSUE TITLE
The `correct()` method in Python 3.7 gives "RuntimeError: generator raised StopIteration"

### ISSUE THREAD

**Issue by vvaezian** [sloria/TextBlob#230]
In Python 3.7 the following gives `RuntimeError: generator raised StopIteration`
````
>>> b = TextBlob("I havv goood speling!")
>>> print(b.correct())
````

I believe [this](https://stackoverflow.com/a/51371879/2445273) SO post describes what needs to be done to address this problem.

Edit: same problem with `spellcheck()` method.

**Comment by wolfxana** [comment]
same issue with .correct()
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\textblob\_text.py", line 365, in _read
    raise StopIteration
StopIteration
