### ISSUE TITLE
ModuleNotFoundError: no module named 'textblob'

### ISSUE THREAD

**Issue by harrisishaq** [sloria/TextBlob#237]
Here i have a proble import text blob with error message ModuleNotFoundError: No module named 'textblob'
I'm using this code `from textblob import TextBlob`

**Comment by sloria** [comment]
This likely isn't an issue with textblob. Are you using a virtualenvironment, and is textblob installed within it?

**Comment by sloria** [comment]
Closing for now. Feel free to re-open if this is still an issue.

**Comment by Sefayay** [comment]
I get the same error and I dont use a virtualenvironment.
---
Traceback (most recent call last):

  File "<ipython-input-1-6c5a198d8ebf>", line 1, in <module>
    from textblob import TextBlob

ModuleNotFoundError: No module named 'textblob'

:(

**Comment by sloria** [comment]
I recommend using a virtualenvironment and installing textblob within it.

**Comment by nemanisagar** [comment]
Sloria, I am using a venv and have textblob there - I am getting the following error 
python3 -m textblob.download_corpora
[nltk_data] Error loading brown: <urlopen error [SSL:
[nltk_data]     CERTIFICATE_VERIFY_FAILED] certificate verify failed:
[nltk_data]     unable to get local issuer certificate (_ssl.c:1108)>
[nltk_data] Error loading punkt: <urlopen error [SSL:
[nltk_data]     CERTIFICATE_VERIFY_FAILED] certificate verify failed:
[nltk_data]     unable to get local issuer certificate (_ssl.c:1108)>
[nltk_data] Error loading wordnet: <urlopen error [SSL:
[nltk_data]     CERTIFICATE_VERIFY_FAILED] certificate verify failed:
[nltk_data]     unable to get local issuer certificate (_ssl.c:1108)>
[nltk_data] Error loading averaged_perceptron_tagger: <urlopen error
[nltk_data]     [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify
[nltk_data]     failed: unable to get local issuer certificate
[nltk_data]     (_ssl.c:1108)>
[nltk_data] Error loading conll2000: <urlopen error [SSL:
[nltk_data]     CERTIFICATE_VERIFY_FAILED] certificate verify failed:
[nltk_data]     unable to get local issuer certificate (_ssl.c:1108)>
[nltk_data] Error loading movie_reviews: <urlopen error [SSL:
[nltk_data]     CERTIFICATE_VERIFY_FAILED] certificate verify failed:
[nltk_data]     unable to get local issuer certificate (_ssl.c:1108)>
Finished.
