### ISSUE TITLE
No module named 'textblob'

### ISSUE THREAD

**Issue by VickyVouk** [sloria/TextBlob#240]
Hi there,
I am a starter of Python and I would like to use 'textblob'. I am a MacOS High Sierra user.
What I tried is to install textblob on a new anaconda environment  by `conda install -c conda-forge textblob`  and `conda install -c conda-forge/label/gcc7 textblob`. It gets installed and then I check on the conda list and textblob is there. However, when I am running `from textblob import TextBlob` on Python I get an error:  **No module named 'textblob'**
How can I resolve this? Thank you in advance

**Comment by irumale** [comment]
I have the same issue but am using window 10. Thanks in anticipation

**Comment by Sburi** [comment]
Would also like the answer. However, I'm using Anaconda and from Spyder when I type this it works. Perhaps Python requires additional commands to see the installed module, but Spyder knows where to look.

**Comment by sloria** [comment]
Make sure that the virtual environment with TextBlob is activated and that `sys.path` looks correct.

```python
import sys
print(sys.path)
```

That should include the `site-packages/` directory *within your virtual environment*.
