### ISSUE TITLE
Word.spellcheck() method returns inconsistent results

### ISSUE THREAD

**Issue by himperion92** [sloria/TextBlob#290]
I'm currently playing around with TextBlob and I found that spellcheck() method is giving me a lot of false positives. For example, for the word 'upload', the spellcheck() output is the following: `[('unload', 1.0)]` where I would expect something more similar to the following: `[('upload', 0.64), ('unload'), 0.36]`. Another example is with the plurals. For instance, given the word "building" the spellcheck() output is the following: `[('buildings', 1.0)]`. Is this the expected behavior? Is there something I'm missing?

**Comment by paridhimnnit** [comment]
Yes this is the expected behaviour. The words you are providing are not in the frequency dictionary so it is correcting them to next possible suggestion. I think textblob needs to add the better and faster spellcorrect algo like symspell for its corrector. Then these problems will be resolved.

**Comment by sloria** [comment]
TextBlob just delegates to pattern.en for spellchecking. Feel free to send a PR with an improved spell checker.
