### ISSUE TITLE
Does Textblob supports non english like german language ??

### ISSUE THREAD

**Issue by suryapa1** [sloria/TextBlob#326]

**Comment by sloria** [comment]
TextBlob supports English out of the box; support for other languages is provided by third-party packages, e.g. https://github.com/markuskiller/textblob-de

**Comment by suryapa1** [comment]
Need suggestion: I could get mix of English and german as input, is it possible to support both languages in one-go. either managing through package?

**Comment by sloria** [comment]
You'll can use a language detection API such as Google Translate. This is no longer supported within TextBlob itself, but you can use the official Google SDK
