### ISSUE TITLE
PyPI 0.16.0 missing

### ISSUE THREAD

**Issue by jayvdb** [sloria/TextBlob#361]
https://github.com/sloria/TextBlob/releases/tag/0.16.0 exists, but it isnt appearing in PyPI which has 0.15.3  as the latest release.

**Comment by igalma** [comment]
Any updates on this issue? It's will be even more important after you will fix the issues created after the api changes

**Comment by sloria** [comment]
it is recommended that you upgrade to a newer textblob version. 0.17.0 and 0.18.0 have been released
