### ISSUE TITLE
SyntaxError: invalid syntax FOR python -m textblob.download_corpora ON Python 3.7.3

### ISSUE THREAD

**Issue by brahmac** [sloria/TextBlob#363]
Command:
python -m textblob.download_corpora

Error:
File "<ipython-input-17-bec4ba3f7ac1>", line 1
    python -m textblob.download_corpora
                     ^
SyntaxError: invalid syntax

Versions:
python: 3.7.3
nltk: 3.5
textblob: 0.15.3

Thanks.

**Comment by Kriti-K** [comment]
I am facing the same issue for Versions:
python: 3.10.4
nltk: 3.7 
textblob: 0.17.1 

were you able to resolve it?

**Comment by sloria** [comment]
these should be fixd in the latest release
