### ISSUE TITLE
Requests error (HTTP Error 404: Not Found)

### ISSUE THREAD

**Issue by Heun11** [sloria/TextBlob#397]
Hello,
I have this issue, it seems to be something with requests package and I don't know how to fix that, please help!
(Image down bellow)
Thanks!
![issue](https://user-images.githubusercontent.com/71566966/133487233-e90fd61e-285f-479b-88b3-3ee7b2a87fa8.png)

**Comment by k-amin07** [comment]
Just had the exact same issue. It appears that [this URL](http://translate.google.com/translate_a/t?client=webapp&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&dt=t&dt=at&ie=UTF-8&oe=UTF-8&otf=2&ssel=0&tsel=0&kc=1) in file textblob/translate.py is no longer valid. Of course this isnt the complete URL that textblob uses and appends some parameters to it but it appears to me that google has changed something with the API.

**Comment by BZ2020** [comment]
Have the same issue in the past 2 days. I thought I had to set up my credit card with google API so google can let my IP to hit the API but that wasnt the case. I was also using textblob 0.15 and thought upgrad could solve the issue. But textblob 0.17 also has the same error. stuck for now.....

**Comment by hinink** [comment]
Same problem [395](https://github.com/sloria/TextBlob/issues/395)

**Comment by Ransomk** [comment]
Yes getting the same here on my end. Keep getting Http 404

**Comment by mzeidhassan** [comment]
same here as well

**Comment by maeril** [comment]
Same here. :(

**Comment by AchuAswin28** [comment]
Use Googletrans to translate the text

import googletrans
from googletrans import Translator

translater = Translator()
value = translater.translate(value)
print(value.src)

To detect the language we can use this...


#397 

Happy Coding!!!!!

**Comment by AchuAswin28** [comment]
Use Googletrans to translate the text

import googletrans
from googletrans import Translator

translater = Translator()
value = translater.translate(value)
print(value.src)

To detect the language we can use this...

#397

Happy Coding!!!!!

**Comment by Heun11** [comment]
@AchuAswin28 
I need translate package that gives me error when you set from_language and you put word from different language!
TextBlob do that as well, but now I have this issue.
But thanks for help :)

**Comment by shubheshswain91** [comment]
Change the URL to below in this installed path /usr/local/lib/python3.7/dist-packages/textblob/translate.py
url = "http://translate.google.com/translate_a/t?client=te&format=html&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&dt=t&dt=at&ie=UTF-8&oe=UTF-8&otf=2&ssel=0&tsel=0&kc=1"

It will work.

**Comment by sloria** [comment]
fixed by https://github.com/sloria/TextBlob/pull/398

**Comment by brianSERP-Ai** [comment]
I'm  having the same issue with translate not working and the above fix is not working either.
