### ISSUE TITLE
Python 3.9 compatibility

### ISSUE THREAD

**Issue by xasg** [sloria/TextBlob#409]
Hello
I want to thank you for the project and comment that checking in PyPi I found that it was compatible up to Python 3.8, however I am in 3.9 and it works properly, I would like to know how it can be updated in PyPi.
I take this opportunity to ask you if Textblob will have support for 3.11, which will be out soon?
Thanks.

**Comment by sloria** [comment]
the latest textblob release is compatible with python 3.8-3.12
