### ISSUE TITLE
error while downloading through python -m textblob.download_corpora 

### ISSUE THREAD

**Issue by ashutosh-sharma-xi** [sloria/TextBlob#417]
A
[nltk_data]     connection attempt failed because the connected party
[nltk_data]     did not properly respond after a period of time, or
[nltk_data]     established connection failed because the connected host
[nltk_data]     has failed to respond>
[nltk_data] Error loading punkt: <urlopen error [WinError 10060] A
[nltk_data]     connection attempt failed because the connected party
[nltk_data]     did not properly respond after a period of time, or
[nltk_data]     established connection failed because the connected host
[nltk_data]     has failed to respond>

**Comment by sloria** [comment]
Try upgrading to the latest version of textblob and re-running the download_corpora script
