### ISSUE TITLE
python -m textblob.download_corpora-Received error 

### ISSUE THREAD

**Issue by MANIKANDAN2112** [sloria/TextBlob#421]
[nltk_data] connection attempt failed because the connected party
[nltk_data] did not properly respond after a period of time, or
[nltk_data] established connection failed because the connected host
[nltk_data] has failed to respond>
[nltk_data] Error loading punkt: <urlopen error [WinError 10060] A
[nltk_data] connection attempt failed because the connected party
[nltk_data] did not properly respond after a period of time, or
[nltk_data] established connection failed because the connected host
[nltk_data] has failed to respond>

**Comment by sloria** [comment]
Try upgrading to the latest version of textblob and re-running the download_corpora script
