### ISSUE TITLE
Running on Google App Engine

### ISSUE THREAD

**Issue by h3nr7** [sloria/TextBlob#43]
The following error has been encountered when trying to run on Google App Engine:

File "/xxxxx/xxxxx/textblob/nltk/data.py", line 76, in <module>
    if os.path.expanduser('~/') != '~/':
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.py", line 260, in expanduser
    userhome = pwd.getpwuid(os.getuid()).pw_dir
KeyError: 'getpwuid(): uid not found: -1'

**Comment by iammangod96** [comment]
1) Go to your cloud console
2) Run the following commands:
pip install -U textblob
python -m textblob.download_corpora

It will download the nltk data with the corpora. Now just deploy your app again and it will work.
