### ISSUE TITLE
Google translating API is not updated 

### ISSUE THREAD

**Issue by Ahnaf702** [sloria/TextBlob#448]
![image](https://github.com/sloria/TextBlob/assets/64384952/cbe1d856-275c-428d-9c69-7792ca91c48c)
![image](https://github.com/sloria/TextBlob/assets/64384952/87d58d47-b113-4b52-9afa-91ead41af263)

**Comment by sloria** [comment]
Google translate functionality has been removed as of 0.18.0, as the API is no longer usable https://textblob.readthedocs.io/en/dev/changelog.html#id2
