### ISSUE TITLE
Attempting to import textblob from within celery task results in SIGSEGV.

### ISSUE THREAD

**Issue by LorenDavie** [sloria/TextBlob#55]
I'm attempting to use TextBlob within a Celery task.  I've isolated the line

import textblob

as causing a SIGSEGV fault, causing the worker process to exit prematurely.  The exactly same code works fine when run in-process (in this case, in the Django dev server).

I would supply more of a stacktrace, but there doesn't seem to be one available since it's a system level, fatal error. The import statement is definitely where it happens however.

If it's a misconfiguration / misuse on my end, any help is appreciated.  Thanks!

**Comment by jschnurr** [comment]
This [Celery](https://github.com/celery/celery/issues/2964#issuecomment-165569834) issue, and that [spaCy](https://github.com/explosion/spaCy/issues/1105#issuecomment-335954369) issue, seem to point toward TextBlob not being fork safe, though I can't reproduce the problem.

This is an old issue; will close it for now, but if anyone comes across it again, please try the workaround in the [Celery](https://github.com/celery/celery/issues/2964#issuecomment-165569834) thread, or post some code that demonstrates it, and we can re-open it.
