### ISSUE TITLE
Deploying TextBlob on remote server

### ISSUE THREAD

**Issue by seekshreyas** [sloria/TextBlob#59]
Hi,

I am trying to deploy `TextBlob` on remote server hosted on heroku. Heroku to my knowledge uses `pip freeze > requirements.txt` to understand the dependencies and install them on the remote server. 

The code works perfectly on my local machine, but on the remote server looks for the `NLTK corpus` and throws an exception. 

How do I install TextBlob dependencies on remote server? 

I am using `virtualenv`

**Comment by anamecheverri** [comment]
I had to run python -m textblob.download_corpora lite  (lite because i only needed basic modules).  This downloads nltk_data to your home directory. I moved that folder to my app folder and added it to the git repository.  Once deployed to heroku, it worked with no issues.

**Comment by anamecheverri** [comment]
oh I also had to increase git http buffer as othwerwise my git push commands were failing after downloading the corpora.  git config --global http.postBuffer 2M

**Comment by pramodthammaiah** [comment]
Is there anyway to load the corpora onto heroku without putting it into the app folder? I'm running into the 1GB limit. Ideally, I have the corpora on AWS S3 and load it into the heroku django app that way.

**Comment by godshall** [comment]
The best way to install the NLTK data on Heroku is to use the built-in `post_compile` hook in the Python buildpack.  By using this approach, you won't have to add the data to your git repo.

https://github.com/heroku/heroku-buildpack-python/blob/master/bin/steps/hooks/post_compile

Here's how to do it:

1. Create a `bin` directory in root of your project
2. Inside the `bin` directory, create `post_compile` and `install_textblob_corpora` text files using the contents of this gist: https://gist.github.com/godshall/a27821c0d1030a096c12 (also added to the bottom of this message)
3. Commit these files to your git repo
4. Set the `NLTK_DATA` environment variable to `/app/nltk_data`.  `$ heroku config:set NLTK_DATA='/app/nltk_data'`
5. Deploy to Heroku

That's it!  

bin/post_compile

    #!/usr/bin/env bash

    if [ -f bin/install_textblob_corpora ]; then
        echo "-----> Running install_textblob_corpora"
        chmod +x bin/install_textblob_corpora
        bin/install_textblob_corpora
    fi

    echo "-----> Post-compile done"

bin/install_textblob_corpora

    #!/usr/bin/env bash

    source $BIN_DIR/utils

    echo "-----> Starting corpora installation"

    # Assumes NLTK_DATA environment variable is already set
    # $ heroku config:set NLTK_DATA='/app/nltk_data'

    # Install the default corpora to NLTK_DATA directory
    python -m textblob.download_corpora

    # Open the NLTK_DATA directory
    cd ${NLTK_DATA}

    # Delete all of the zip files in the NLTK DATA directory
    find . -name "*.zip" -type f -delete

    echo "-----> Finished corpora installation"

**Comment by pramodthammaiah** [comment]
Thanks!

**Comment by vmksharma** [comment]
Hello folks I am facing exactly same issue but on IBM cloud
error:

Error while running the app:
textblob.exceptions.MissingCorpusError
MissingCorpusError: 
Looks like you are missing some required data for this feature.

Can I get some pointers on how to download corpora on bluemix virtual environment

**Comment by BatTzionMetzger** [comment]
Add this file to my root
[nltk.txt](https://github.com/sloria/TextBlob/files/6178254/nltk.txt)
