### ISSUE TITLE
Reading training data from database

### ISSUE THREAD

**Issue by acquayefrank** [sloria/TextBlob#73]
Hi, 
I'm wondering how I could easily read training data from a database. 
PS: I'm using django.

**Comment by sloria** [comment]
@acquayefrank See the docs on registering custom file formats: http://textblob.readthedocs.org/en/dev/api_reference.html#module-textblob.formats . Also see https://github.com/sloria/TextBlob/issues/67#issuecomment-55539402 for an example.
