### ISSUE TITLE
Classifiers Taking Days To Create

### ISSUE THREAD

**Issue by mrbirl** [sloria/TextBlob#77]
I'm testing Naive Bayes classifier. I have a training set of 60,000 jobs, each one mapped to one of 30 possible tags.

Unfortunately the classifier won't build - after leaving a high powered AWS instance for almost 48 hours it still hadn't built the classifier and eventually failed.

Is it possible to use this library with a someway large training list like this?

**Comment by IvRRimum** [comment]
Did you resolve this ?

I am building big scale classifiers too..

Would be great to leave your feedback for others.

**Comment by flavio-clesio-movile** [comment]
Hi I'm facing the same problem. 

I'll test with xlarge machine in AWS to see if there's some problem in my machine.

**Comment by sloria** [comment]
#136 is now merged and released.
