### ISSUE TITLE
Analyzing Forum Posts

### ISSUE THREAD

**Issue by kadnan** [sloria/TextBlob#79]
I am a python developer and trying to work on a pet project deals with analyzing different forum posts and try to get the crux of it. Since I am new in ML/states.

What actually I am interested to do is to write a program that will read different job posts and will help me to figure out following things:
- What technology/Knowledge required(Java, Photoshop, UI etc)
- Remote or onSite or offer Relocation
- Freelance gig or a FT/PT job
- Is Budget mentioned?

Though I am ignorant but what I guess some classifier algorithm should be able to get the idea of a post but I need your guidance in this regard.

**Comment by jschnurr** [comment]
Closed for inactivity.
