### ISSUE TITLE
(after 0.5.1) - AttributeError: 'module' object has no attribute 'compat'

### ISSUE THREAD

**Issue by ghost** [sloria/TextBlob#8]
Traceback (most recent call last):
  File "sentiment.py", line 1, in <module>
    from text.blob import TextBlob
  File "/usr/local/lib/python2.7/dist-packages/text/blob.py", line 149, in <module>
    @nltk.compat.python_2_unicode_compatible
AttributeError: 'module' object has no attribute 'compat'

**Comment by karnikamit** [comment]
when I run this,
from textblob import TextBlob
wiki = TextBlob("Python is a high-level, general-purpose programming language.")
print wiki.noun_phrases

I get the error
AttributeError: 'module' object has no attribute 'register_dialect'
can anyone help me out here? any help is appreciated.
