### ISSUE TITLE
Limit on the usage of TextBlob?

### ISSUE THREAD

**Issue by HongHuangNeu** [sloria/TextBlob#81]
Hi,

Are there any limit on the usage of TextBlob API, such as the maximum number of API calls per day? I am not using the translation service of TextBlob.

Thank you!

**Comment by sloria** [comment]
@HongHuangNeu Can you clarify what you mean by API calls? Aside from the translator module, TextBlob does not make any HTTP requests to 3rd parties.

**Comment by HongHuangNeu** [comment]
Thanks for the reply. 
I want to do text classification with Naive Bayes in TextBlob. So there are no limit on how many times I can call a method provided by TextBlob API?

**Comment by sloria** [comment]
There are no usage limits to using TextBlob.

**Comment by saurabhbidwai** [comment]
textBlob.translate() has limitations of 1000 calls/day

**Comment by soulmachine** [comment]
Does `textblob.translate()` still has the limitation of 1000 calls/day? I got en error: `Too many requests`
