### ISSUE TITLE
text argument must be a string not a Series

### ISSUE THREAD

**Issue by kimkraunz** [sloria/TextBlob#82]
I'm getting the following error when I try to use the sentiment property:
The `text` argument passed to `__init__(text)` must be a string, not <class 'pandas.core.series.Series'>

I'm trying to run:

text = df['blurb'].apply(str)
blob = TextBlob(text)
sentiment= blob.sentiment

Can you please advise me how to pass a Series through TextBlob to do sentient analysis.  The error seems to be coming from line 2.  I've tried to write as a loop but I still get the same error.

**Comment by avinav** [comment]
It is possible that your text will be of 'Series' type. And you are trying to create  a blob with that type instead of string. Error will be like:
The `text` argument passed to `__init__(text)` must be a string, not <class 'pandas.core.series.Series'>
