### ISSUE TITLE
Translation adds whitespaces around punctuation chars

### ISSUE THREAD

**Issue by AdrianLC** [sloria/TextBlob#83]
Hello,

```
In [1]: import textblob

In [2]: corpus = textblob.TextBlob("Hola, me llamo Adrián! Cómo estás? Yo bien")

In [3]: corpus.translate()
Out[3]: TextBlob("Hello , my name is Adrian ! How are you? I good")
```
Notice the space before the comma and exclamation.

Is this expected behaviour? Is there a known solution to avoid this?
(Debugging shows that the json5 comes already with the spaces.)

Thank you!

**Comment by sloria** [comment]
Fixed by https://github.com/sloria/TextBlob/pull/84
