### ISSUE TITLE
Problem with importing TextBlob

### ISSUE THREAD

**Issue by alexlu3211** [sloria/TextBlob#86]
When I use type in the command inside shell, it works pretty well and no errors occur:
    import textblob
    from textblob import TextBlob
However, when I put these commands into the py file, and run it, it says
cannot import name "TextBlob"

Please help me with it. Thanks a lot

**Comment by sloria** [comment]
Do you have a module named `textblob.py` in your project?

**Comment by azizyarahmadi** [comment]
I have the same problem Sloria. in this path: C:\Python27\Lib\site-packages\textblob
there is no file called textblob.py
Also I can run the code line-by-line in cmd or anaconda but whenever I try to run the py file,I get the same error.

**Comment by kengz** [comment]
Had the same issue; accidentally named my own source code `textblob.py` and `textblob.pyc`. Renamed them and it worked again.

**Comment by sarojkumar007** [comment]
I have the same issue @alexlu3211 . I don't have any file names textblob.py, still problem persists. Please Help me out.

**Comment by sloria** [comment]
If you're running into this, it's likely not a textblob-specific issue. Make sure that 1) nothing is shadowing the `textblob` import and 2) that you have the correct virtualenv activated.
