### ISSUE TITLE
Textblob object to string 

### ISSUE THREAD

**Issue by Sebiti** [sloria/TextBlob#89]
Is there a way to invert Textblob creation? Instead of turning a string text into a Textblob, extract the text from the textblob?

**Comment by nmstoker** [comment]
I ran into this just earlier, and all it needs is an explicit conversion to string.  Here's an example (**in Python 3**):

    from textblob import TextBlob
     tb = TextBlob('An example sentence.')
    print('\t' + str(tb))

It also works the same within sentences (ie if you've done: `for s in tb.sentences`)

**Comment by Sebiti** [comment]
Thank you nmstoker. I admit it didn't even cross my mind.
