### ISSUE TITLE
Add support for Python 3.5

### ISSUE THREAD

**Issue by jimmycallin** [sloria/TextBlob#93]
I don't know if this is a conda issue or textblob issue, but currently textblob using conda isn't supporting Python 3.5:

› conda create -n py35 python=3.5 textblob
Fetching package metadata: ......
Solving package specifications: ..
Error: Unsatisfiable package specifications.

Hint: the following packages conflict with each other:
  - python 3.5*
  - textblob

**Comment by sloria** [comment]
I've just uploaded a OSX-py35 build to anaconda.org.

You should now be able to install it with:

```
conda install -c https://conda.anaconda.org/sloria textblob
```

**Comment by jimmycallin** [comment]
Thanks!
